import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Filme filme = new Filme();
        filme.nome = "Velozes e furiosos: Desafio em Tokyo";
        filme.duração = 106;
        filme.lançamento = 2006;
        Filme filme1 = new Filme();
        filme1.nome = "ET";
        filme1.duração = 105;
        filme1.lançamento = 1982;
        Filme filme2 = new Filme();
        filme2.nome = "Mudança de Habitos";
        filme2.duração = 100;
        filme2.lançamento = 1992;
        Filme filme3 = new Filme();
        filme3.nome = "O iluminado";
        filme3.duração = 146.0;
        filme3.lançamento = 1980;
        Filme filme4 = new Filme();
        filme4.nome = "Esqueceram de mim";
        filme4.duração = 103.0;
        filme4.lançamento = 1990;
        Filme filme5 = new Filme();
        filme5.nome = "Top Gun";
        filme5.duração = 100.0;
        filme5.lançamento = 1986;
        Filme filme6 = new Filme();
        filme6.nome = "Gente Grande";
        filme6.duração = 102.0;
        filme6.lançamento = 2010;
        Filme filme7 = new Filme();
        filme7.nome = "Esposa de mentirinha";
        filme7.duração = 117.0;
        filme7.lançamento = 2011;
        Filme filme8 = new Filme();
        filme8.nome = "Divertidamente";
        filme8.duração = 95.0;
        filme8.lançamento = 2015;
        Filme filme9 = new Filme();
        filme9.nome = "Zootopia";
        filme9.duração = 108.0;
        filme9.lançamento = 2016;
        filme.fichaTecnica();
        filme.longo(160.0);
        filme.ano(2006);
        filme.titulo("Velozes e furiosos: Desafio em Tokyo");
//        System.out.println("___________________________________________");
//        filme1.fichaTecnica();
//        filme1.longo(105.0);
//        filme1.ano(1982);
//        filme1.titulo("ET");
//        System.out.println("___________________________________________");
//        filme2.fichaTecnica();
//        filme2.longo(100);
//        filme2.ano(1992);
//        filme2.titulo("Mudança de Habitos");
//        System.out.println("___________________________________________");
//        filme3.fichaTecnica();
//        filme3.longo(146.0);
//        filme3.ano(1980);
//        filme3.titulo("O iluminado");
//        System.out.println("___________________________________________");
//        filme4.fichaTecnica();
//        filme4.longo(103.0);
//        filme4.ano(1990);
//        filme4.titulo("Esqueceram de mim");
//        System.out.println("___________________________________________");
//        filme5.fichaTecnica();
//        filme5.longo(100.0);
//        filme5.ano(1986);
//        filme5.titulo("Top gun");
//        System.out.println("___________________________________________");
//        filme6.fichaTecnica();
//        filme6.longo(102.0);
//        filme6.ano(2010);
//        filme6.titulo("Gente grande");
        System.out.println("___________________________________________");
        filme7.fichaTecnica();
        filme7.longo(117.0);
        filme7.ano(2011);
        filme7.titulo("Esposa de mentirinha");
        System.out.println("___________________________________________");
//        filme8.fichaTecnica();
//        filme8.longo(95.0);
//        filme8.ano(2015);
//        filme8.titulo("Divertidamente");
//        System.out.println("___________________________________________");
        filme9.fichaTecnica();
        filme9.longo(108.0);
        filme9.ano(2016);
        filme9.titulo("Zootopia");
        System.out.println("**********************************************");
        Temperatura temperatura = new Temperatura();
        temperatura.maxima = 35;
        temperatura.minima = 28;
        temperatura.momento = 32;
        System.out.println("___________________________________________");
        Temperatura temperatura1 = new Temperatura();
        temperatura1.maxima = 12;
        temperatura1.minima = 5;
        temperatura1.momento = 7;
        System.out.println("___________________________________________");
        Temperatura temperatura2 = new Temperatura();
        temperatura2.maxima = 42;
        temperatura2.minima = 37;
        temperatura2.momento = 39;
        System.out.println("___________________________________________");
        temperatura.previsao();
        temperatura.quente(35);
        temperatura.frio(28);
        temperatura.recomendacao(32);
        System.out.println("___________________________________________");
        temperatura1.previsao();
        temperatura1.quente(12);
        temperatura1.frio(5);
        temperatura1.recomendacao(7);
        System.out.println("___________________________________________");
        temperatura2.previsao();
        temperatura2.quente(42);
        temperatura2.frio(37);
        temperatura2.recomendacao(39);
        System.out.println("**********************************************");
        Alimento alimento = new Alimento();
        alimento.peso = 103.7;
        alimento.caloria = 227.9;
        alimento.carboidrato = 107.3;
        Alimento alimento1 = new Alimento();
        alimento1.peso = 350.5;
        alimento1.caloria = 4000.1;
        alimento1.carboidrato = 150.8;
        Alimento alimento2 = new Alimento();
        alimento2.peso = 75.5;
        alimento2.caloria = 834.3;
        alimento2.carboidrato = 67.9;
        alimento.prato();
        alimento.quantidade(103.7);
        alimento.carboidratos(227);
        alimento.calorias(107.3);
        System.out.println("___________________________________________");
        alimento1.prato();
        alimento1.quantidade(350.5);
        alimento1.carboidratos(150.8);
        alimento1.calorias(4000.1);
        System.out.println("___________________________________________");
        alimento2.prato();
        alimento2.quantidade(75.5);
        alimento2.carboidratos(834.3);
        alimento2.calorias(67.9);
        System.out.println("**********************************************");
        Musica musica = new Musica();
        musica.nome = "Bohemian Rhapsody";
        musica.video = "TEM";
        musica.tempo = 359;
        musica.ano = 1975;
        Musica musica1 = new Musica();
        musica1.nome = "Toxic";
        musica1.video = "TEM";
        musica1.tempo = 199;
        musica1.ano = 2003;
        Musica musica2 = new Musica();
        musica2.nome = "Talking too the moon";
        musica2.video = "NAO TEM";
        musica2.tempo = 214;
        musica2.ano = 2010;
        musica.informacoes();
        musica.clipe("TEM");
        musica.duracao(359);
        musica.lancamento(1975);
        System.out.println("___________________________________________");
        musica1.informacoes();
        musica1.clipe("TEM");
        musica1.duracao(199);
        musica1.lancamento(2003);
        System.out.println("___________________________________________");
        musica2.informacoes();
        musica2.clipe("NAO TEM");
        musica2.duracao(214);
        musica2.lancamento(2010);
        System.out.println("**********************************************");
        Cachorro cachorro = new Cachorro();
        cachorro.nome = "Lilica";
        cachorro.raca = "Vira-lata";
        cachorro.cor = "amarela";
        cachorro.velocidade = 22;
        Cachorro cachorro1 = new Cachorro();
        cachorro1.nome = "Amora";
        cachorro1.raca = "Golden";
        cachorro1.cor = "amarela";
        cachorro1.velocidade = 20;
        Cachorro cachorro2 = new Cachorro();
        cachorro2.nome = "Luna";
        cachorro2.raca = "Labrador";
        cachorro2.cor = "preto";
        cachorro2.velocidade = 20;
        cachorro.sobre();
        cachorro.tipo("Vira-lata");
        cachorro.corrida(22);
        cachorro.pelo("amarela");
        System.out.println("___________________________________________");
        cachorro1.sobre();
        cachorro1.tipo("Golden");
        cachorro1.corrida(20);
        cachorro1.pelo("amarela");
        System.out.println("___________________________________________");
        cachorro2.sobre();
        cachorro2.tipo("Labrador");
        cachorro2.corrida(20);
        cachorro2.pelo("preto");

    }
}
