
public class Main {

    public static void main(String[] args) {
        Filme filme = new Filme();
        filme.nome = "Velozes e furiosos: Desafio em Tokyo";
        filme.duração = 106.0;
        filme.lançamento = 2006.0;
        Filme filme1 = new Filme();
        filme1.nome = "ET";
        filme1.duração = 105.0;
        filme1.lançamento = 1982.0;
        Filme filme2 = new Filme();
        filme2.nome = "Mudança de Habitos";
        filme2.duração = 100.0;
        filme2.lançamento = 1992.0;
        Filme filme3 = new Filme();
        filme3.nome = "O iluminado";
        filme3.duração = 146.0;
        filme3.lançamento = 1980.0;
        Filme filme4 = new Filme();
        filme4.nome = "Esqueceram de mim";
        filme4.duração = 103.0;
        filme4.lançamento = 1990.0;
        Filme filme5 = new Filme();
        filme5.nome = "Top Gun";
        filme5.duração = 100.0;
        filme5.lançamento = 1986.0;
        Filme filme6 = new Filme();
        filme6.nome = "Gente Grande";
        filme6.duração = 102.0;
        filme6.lançamento = 2010.0;
        Filme filme7 = new Filme();
        filme7.nome = "Esposa de mentirinha";
        filme7.duração = 117.0;
        filme7.lançamento = 2011.0;
        Filme filme8 = new Filme();
        filme8.nome = "Divertidamente";
        filme8.duração = 95.0;
        filme8.lançamento = 2015.0;
        Filme filme9 = new Filme();
        filme9.nome = "Zootopia";
        filme9.duração = 108.0;
        filme9.lançamento = 2016.0;
        filme.fichaTecnica();
        filme.longo(160.0);
        filme.ano(2006);
        filme.titulo("Velozes e furiosos: Desafio em Tokyo");
        System.out.println("___________________________________________");
        filme1.fichaTecnica();
        filme1.longo(105.0);
        filme1.ano(1982);
        filme1.titulo("ET");
        System.out.println("___________________________________________");
        filme2.fichaTecnica();
        filme2.longo(100.0);
        filme2.ano(1992);
        filme2.titulo("Mudança de Habitos");
        System.out.println("___________________________________________");
        filme3.fichaTecnica();
        filme3.longo(146.0);
        filme3.ano(1980);
        filme3.titulo("O iluminado");
        System.out.println("___________________________________________");
        filme4.fichaTecnica();
        filme4.longo(103.0);
        filme4.ano(1990);
        filme4.titulo("Esqueceram de mim");
        System.out.println("___________________________________________");
        filme5.fichaTecnica();
        filme5.longo(100.0);
        filme5.ano(1986);
        filme5.titulo("Top gun");
        System.out.println("___________________________________________");
        filme6.fichaTecnica();
        filme6.longo(102.0);
        filme6.ano(2010);
        filme6.titulo("Gente grande");
        System.out.println("___________________________________________");
        filme7.fichaTecnica();
        filme7.longo(117.0);
        filme7.ano(2011);
        filme7.titulo("Esposa de mentirinha");
        System.out.println("___________________________________________");
        filme8.fichaTecnica();
        filme8.longo(95.0);
        filme8.ano(2015);
        filme8.titulo("Divertidamente");
        System.out.println("___________________________________________");
        filme9.fichaTecnica();
        filme9.longo(108.0);
        filme9.ano(2016);
        filme9.titulo("Zootopia");
    }
}
